# config context path to "/" by setting an empty string
server:
  contextPath: 
  port: 4000  

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true 
  
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: create-drop
          
  datasource:
    url: jdbc:mysql://localhost:3306/base?autoReconnect=true&useSSL=false    
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: ejemplo@outlook.com
    password: 0123456789
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp-mail.outlook.com

jwt:
  header: Authorization
  secret: mySecret
  expiration: 3600
  route:
    authentication:
      path: /api/auth
      refresh: /api/refresh
      isTokenValid: /api/token/
  
#logging:
#  level:
#    org.springframework:
#      security: DEBUG